services:
  - type: web
    name: libratrack-preview
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: "20"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
